import type { Flour } from "./types";

export const FLOURS: Flour[] = [
  {
    id: "bread",
    name: "Bread flour",
    short: "Bread",
    protein: 12.7,
    sweetSpot: 72,
    ceiling: 78,
    family: "white",
    notes: "High-gluten workhorse. Holds a taut skin through high hydration.",
  },
  {
    id: "ap",
    name: "All-purpose",
    short: "AP",
    protein: 11.0,
    sweetSpot: 68,
    ceiling: 74,
    family: "white",
    notes: "Softer gluten. Keep true hydration modest or expect a slack mix.",
  },
  {
    id: "tipo00",
    name: "00 pizza",
    short: "00",
    protein: 12.2,
    sweetSpot: 64,
    ceiling: 70,
    family: "white",
    notes: "Extensible, fine mill. Pizza and focaccia — not a high-hydration boule.",
  },
  {
    id: "t80",
    name: "High-extraction T80",
    short: "T80",
    protein: 12.0,
    sweetSpot: 74,
    ceiling: 80,
    family: "white",
    notes: "Cream crumb, more ash. Drinks a little more than straight white.",
  },
  {
    id: "ww",
    name: "Whole wheat",
    short: "WW",
    protein: 13.5,
    sweetSpot: 78,
    ceiling: 86,
    family: "whole",
    notes: "Bran cuts gluten and drinks water. Autolyse 30–45 min.",
  },
  {
    id: "whiteww",
    name: "White whole wheat",
    short: "White WW",
    protein: 13.0,
    sweetSpot: 76,
    ceiling: 84,
    family: "whole",
    notes: "Milder bran flavor, still thirsty. Blend-friendly.",
  },
  {
    id: "fresh",
    name: "Fresh-milled hard wheat",
    short: "Fresh mill",
    protein: 14.0,
    sweetSpot: 82,
    ceiling: 88,
    family: "whole",
    notes: "Enzymatically active and very thirsty. Mix gently; watch proteolysis.",
  },
  {
    id: "rye-light",
    name: "Light rye",
    short: "Lt rye",
    protein: 8.5,
    sweetSpot: 80,
    ceiling: 90,
    family: "rye",
    notes: "Pentosans make it sticky, not extensible. Blend or pan-bake.",
  },
  {
    id: "rye-dark",
    name: "Dark rye",
    short: "Dk rye",
    protein: 9.0,
    sweetSpot: 92,
    ceiling: 102,
    family: "rye",
    notes: "Almost no gluten net. High ceiling, scoop-and-pan technique.",
  },
  {
    id: "spelt",
    name: "Spelt",
    short: "Spelt",
    protein: 12.0,
    sweetSpot: 68,
    ceiling: 75,
    family: "ancient",
    notes: "Extensible and slack. Lower hydration than the protein number suggests.",
  },
  {
    id: "einkorn",
    name: "Einkorn",
    short: "Einkorn",
    protein: 14.5,
    sweetSpot: 62,
    ceiling: 70,
    family: "ancient",
    notes: "Weak, golden, sticky. Treat the ceiling as a hard wall.",
  },
  {
    id: "kamut",
    name: "Kamut (Khorasan)",
    short: "Kamut",
    protein: 14.5,
    sweetSpot: 70,
    ceiling: 78,
    family: "ancient",
    notes: "Buttery, strong enough for a boule. Golden crumb.",
  },
  {
    id: "durum",
    name: "Durum / semolina",
    short: "Durum",
    protein: 13.0,
    sweetSpot: 68,
    ceiling: 75,
    family: "specialty",
    notes: "Pasta wheat. Color and bite; blend 10–30% into country doughs.",
  },
  {
    id: "custom",
    name: "Custom flour",
    short: "Custom",
    protein: 12.0,
    sweetSpot: 72,
    ceiling: 78,
    family: "specialty",
    notes: "Set protein and ceiling to match the bag in front of you.",
  },
];

export const FLOUR_BY_ID: Record<string, Flour> = Object.fromEntries(
  FLOURS.map((f) => [f.id, f]),
);

export function resolveFlour(
  id: string,
  custom: { name: string; protein: number; ceiling: number },
): Flour {
  if (id === "custom") {
    return {
      id: "custom",
      name: custom.name.trim() || "Custom flour",
      short: "Custom",
      protein: custom.protein,
      sweetSpot: Math.max(50, custom.ceiling - 6),
      ceiling: custom.ceiling,
      family: "specialty",
      notes: "Your mill, your ceiling.",
    };
  }
  return FLOUR_BY_ID[id] ?? FLOUR_BY_ID.bread;
}
