/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesFlourHydrationCeilingRouteImport } from './routes/guides/flour-hydration-ceiling'
import { Route as GuidesSourdoughCrumbTroubleshootingRouteImport } from './routes/guides/sourdough-crumb-troubleshooting'
import { Route as GuidesTemperatureFermentationMatrixRouteImport } from './routes/guides/temperature-fermentation-matrix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFlourHydrationCeilingRoute =
  GuidesFlourHydrationCeilingRouteImport.update({
    id: '/guides/flour-hydration-ceiling',
    path: '/guides/flour-hydration-ceiling',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSourdoughCrumbTroubleshootingRoute =
  GuidesSourdoughCrumbTroubleshootingRouteImport.update({
    id: '/guides/sourdough-crumb-troubleshooting',
    path: '/guides/sourdough-crumb-troubleshooting',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesTemperatureFermentationMatrixRoute =
  GuidesTemperatureFermentationMatrixRouteImport.update({
    id: '/guides/temperature-fermentation-matrix',
    path: '/guides/temperature-fermentation-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
  '/guides/sourdough-crumb-troubleshooting': typeof GuidesSourdoughCrumbTroubleshootingRoute
  '/guides/temperature-fermentation-matrix': typeof GuidesTemperatureFermentationMatrixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
  '/guides/sourdough-crumb-troubleshooting': typeof GuidesSourdoughCrumbTroubleshootingRoute
  '/guides/temperature-fermentation-matrix': typeof GuidesTemperatureFermentationMatrixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
  '/guides/sourdough-crumb-troubleshooting': typeof GuidesSourdoughCrumbTroubleshootingRoute
  '/guides/temperature-fermentation-matrix': typeof GuidesTemperatureFermentationMatrixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guides/flour-hydration-ceiling'
    | '/guides/sourdough-crumb-troubleshooting'
    | '/guides/temperature-fermentation-matrix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guides/flour-hydration-ceiling'
    | '/guides/sourdough-crumb-troubleshooting'
    | '/guides/temperature-fermentation-matrix'
  id:
    | '__root__'
    | '/'
    | '/guides/flour-hydration-ceiling'
    | '/guides/sourdough-crumb-troubleshooting'
    | '/guides/temperature-fermentation-matrix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesFlourHydrationCeilingRoute: typeof GuidesFlourHydrationCeilingRoute
  GuidesSourdoughCrumbTroubleshootingRoute: typeof GuidesSourdoughCrumbTroubleshootingRoute
  GuidesTemperatureFermentationMatrixRoute: typeof GuidesTemperatureFermentationMatrixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/flour-hydration-ceiling': {
      id: '/guides/flour-hydration-ceiling'
      path: '/guides/flour-hydration-ceiling'
      fullPath: '/guides/flour-hydration-ceiling'
      preLoaderRoute: typeof GuidesFlourHydrationCeilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/sourdough-crumb-troubleshooting': {
      id: '/guides/sourdough-crumb-troubleshooting'
      path: '/guides/sourdough-crumb-troubleshooting'
      fullPath: '/guides/sourdough-crumb-troubleshooting'
      preLoaderRoute: typeof GuidesSourdoughCrumbTroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/temperature-fermentation-matrix': {
      id: '/guides/temperature-fermentation-matrix'
      path: '/guides/temperature-fermentation-matrix'
      fullPath: '/guides/temperature-fermentation-matrix'
      preLoaderRoute: typeof GuidesTemperatureFermentationMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesFlourHydrationCeilingRoute: GuidesFlourHydrationCeilingRoute,
  GuidesSourdoughCrumbTroubleshootingRoute:
    GuidesSourdoughCrumbTroubleshootingRoute,
  GuidesTemperatureFermentationMatrixRoute:
    GuidesTemperatureFermentationMatrixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
