/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesFlourHydrationCeilingRouteImport } from './routes/guides/flour-hydration-ceiling'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFlourHydrationCeilingRoute =
  GuidesFlourHydrationCeilingRouteImport.update({
    id: '/guides/flour-hydration-ceiling',
    path: '/guides/flour-hydration-ceiling',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides/flour-hydration-ceiling': typeof GuidesFlourHydrationCeilingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guides/flour-hydration-ceiling'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guides/flour-hydration-ceiling'
  id: '__root__' | '/' | '/guides/flour-hydration-ceiling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesFlourHydrationCeilingRoute: typeof GuidesFlourHydrationCeilingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/flour-hydration-ceiling': {
      id: '/guides/flour-hydration-ceiling'
      path: '/guides/flour-hydration-ceiling'
      fullPath: '/guides/flour-hydration-ceiling'
      preLoaderRoute: typeof GuidesFlourHydrationCeilingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesFlourHydrationCeilingRoute: GuidesFlourHydrationCeilingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
